**Data Cleaning for LA county census data**

In [1]:
import pandas as pd

In [2]:
la_county_df = pd.read_csv('./data/census_data/LA_County_Data.csv', low_memory=False)

In [3]:
la_county_df.head()

,GEO_ID,NAME,DP05_0001E,DP05_0001EA,DP05_0001M,DP05_0001MA,DP05_0002E,DP05_0002M,DP05_0002MA,DP05_0002EA,...,DP05_0087PEA,DP05_0088PE,DP05_0088PM,DP05_0088PMA,DP05_0088PEA,DP05_0089PE,DP05_0089PM,DP05_0089PMA,DP05_0089PEA,Unnamed: 714
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Annotation of Estimate!!SEX AND AGE!!Total pop...,Margin of Error!!SEX AND AGE!!Total population,Annotation of Margin of Error!!SEX AND AGE!!To...,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Annotation of Margin of Error!!SEX AND AGE!!To...,Annotation of Estimate!!SEX AND AGE!!Total pop...,...,"Annotation of Percent!!CITIZEN, VOTING AGE POP...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",Annotation of Percent Margin of Error!!CITIZEN...,"Annotation of Percent!!CITIZEN, VOTING AGE POP...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",Annotation of Percent Margin of Error!!CITIZEN...,"Annotation of Percent!!CITIZEN, VOTING AGE POP...",NaN
1,1400000US06037101110,"Census Tract 1011.10, Los Angeles County, Cali...",3879,NaN,480,NaN,1944,280,NaN,NaN,...,NaN,46.6,4.0,NaN,NaN,53.4,4.0,NaN,NaN,NaN
2,1400000US06037101122,"Census Tract 1011.22, Los Angeles County, Cali...",4247,NaN,875,NaN,2066,477,NaN,NaN,...,NaN,51.3,4.2,NaN,NaN,48.7,4.2,NaN,NaN,NaN
3,1400000US06037101220,"Census Tract 1012.20, Los Angeles County, Cali...",3583,NaN,486,NaN,1692,262,NaN,NaN,...,NaN,46.9,5.4,NaN,NaN,53.1,5.4,NaN,NaN,NaN
4,1400000US06037101221,"Census Tract 1012.21, Los Angeles County, Cali...",3723,NaN,721,NaN,1954,470,NaN,NaN,...,NaN,57.2,9.0,NaN,NaN,42.8,9.0,NaN,NaN,NaN

In [4]:
la_county_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 715 columns):
 #    Column        Non-Null Count  Dtype
---   ------        --------------  -----
 0    GEO_ID        2499 non-null   object
 1    NAME          2499 non-null   object
 2    DP05_0001E    2499 non-null   object
 3    DP05_0001EA   1 non-null      object
 4    DP05_0001M    2499 non-null   object
 5    DP05_0001MA   1 non-null      object
 6    DP05_0002E    2499 non-null   object
 7    DP05_0002M    2499 non-null   object
 8    DP05_0002MA   1 non-null      object
 9    DP05_0002EA   1 non-null      object
 10   DP05_0003E    2499 non-null   object
 11   DP05_0003M    2499 non-null   object
 12   DP05_0003MA   1 non-null      object
 13   DP05_0003EA   1 non-null      object
 14   DP05_0004E    2499 non-null   object
 15   DP05_0004M    2499 non-null   object
 16   DP05_0004MA   25 non-null     object
 17   DP05_0004EA   25 non-null     object
 18   DP05_0005E    2499 non-null   object
 19   DP05_0005M    2499 non-null   object
 20   DP05_0005MA   1 non-null      object
 21   DP05_0005EA   1 non-null      object
 22   DP05_0006E    2499 non-null   object
 23   DP05_0006M    2499 non-null   object
 24   DP05_0006MA   1 non-null      object
 25   DP05_0006EA   1 non-null      object
 26   DP05_0007E    2499 non-null   object
 27   DP05_0007M    2499 non-null   object
 28   DP05_0007MA   1 non-null      object
 29   DP05_0007EA   1 non-null      object
 30   DP05_0008E    2499 non-null   object
 31   DP05_0008EA   1 non-null      object
 32   DP05_0008M    2499 non-null   object
 33   DP05_0008MA   1 non-null      object
 34   DP05_0009E    2499 non-null   object
 35   DP05_0009M    2499 non-null   object
 36   DP05_0009MA   1 non-null      object
 37   DP05_0009EA   1 non-null      object
 38   DP05_0010E    2499 non-null   object
 39   DP05_0010M    2499 non-null   object
 40   DP05_0010MA   1 non-null      object
 41   DP05_0010EA   1 non-null      object
 42   DP05_0011E    2499 non-null   object
 43   DP05_0011M    2499 non-null   object
 44   DP05_0011MA   1 non-null      object
 45   DP05_0011EA   1 non-null      object
 46   DP05_0012E    2499 non-null   object
 47   DP05_0012EA   1 non-null      object
 48   DP05_0012M    2499 non-null   object
 49   DP05_0012MA   1 non-null      object
 50   DP05_0013E    2499 non-null   object
 51   DP05_0013M    2499 non-null   object
 52   DP05_0013MA   1 non-null      object
 53   DP05_0013EA   1 non-null      object
 54   DP05_0014E    2499 non-null   object
 55   DP05_0014M    2499 non-null   object
 56   DP05_0014MA   1 non-null      object
 57   DP05_0014EA   1 non-null      object
 58   DP05_0015E    2499 non-null   object
 59   DP05_0015M    2499 non-null   object
 60   DP05_0015MA   1 non-null      object
 61   DP05_0015EA   1 non-null      object
 62   DP05_0016E    2499 non-null   object
 63   DP05_0016M    2499 non-null   object
 64   DP05_0016MA   1 non-null      object
 65   DP05_0016EA   1 non-null      object
 66   DP05_0017E    2499 non-null   object
 67   DP05_0017M    2499 non-null   object
 68   DP05_0017MA   1 non-null      object
 69   DP05_0017EA   1 non-null      object
 70   DP05_0018E    2499 non-null   object
 71   DP05_0018EA   23 non-null     object
 72   DP05_0018M    2499 non-null   object
 73   DP05_0018MA   23 non-null     object
 74   DP05_0019E    2499 non-null   object
 75   DP05_0019M    2499 non-null   object
 76   DP05_0019MA   1 non-null      object
 77   DP05_0019EA   1 non-null      object
 78   DP05_0020E    2499 non-null   object
 79   DP05_0020M    2499 non-null   object
 80   DP05_0020MA   1 non-null      object
 81   DP05_0020EA   1 non-null      object
 82   DP05_0021E    2499 non-null   object
 83   DP05_0021M    2499 non-null   object
 84   DP05_0021MA   1 non-null      object
 85   DP05_0021EA   1 non-null      object
 86   DP05_0022E    2499 non-null   object
 87   DP05_0022M    2499 non-null   object
 88   DP05_0022MA   1 non-null      object
 89   DP05_0022EA   1 non-null      object
 90   DP05_0023E    2499 non-null   object
 91   DP05_0023EA   1 non-null      object
 92   DP05_0023M    2499 non-null   object
 93   DP05_0023MA   1 non-null      object
 94   DP05_0024E    2499 non-null   object
 95   DP05_0024M    2499 non-null   object
 96   DP05_0024MA   1 non-null      object
 97   DP05_0024EA   1 non-null      object
 98   DP05_0025E    2499 non-null   object
 99   DP05_0025M    2499 non-null   object
 100  DP05_0025MA   1 non-null      object
 101  DP05_0025EA   1 non-null      object
 102  DP05_0026E    2499 non-null   object
 103  DP05_0026M    2499 non-null   object
 104  DP05_0026MA   1 non-null      object
 105  DP05_0026EA   1 non-null      object
 106  DP05_0027E    2499 non-null   object
 107  DP05_0027M    2499 non-null   object
 108  DP05_0027MA   1 non-null      object
 109  DP05_0027EA   1 non-null      object
 110  DP05_0028E    2499 non-null   object
 111  DP05_0028M    2499 non-null   object
 112  DP05_0028MA   26 non-null     object
 113  DP05_0028EA   26 non-null     object
 114  DP05_0029E    2499 non-null   object
 115  DP05_0029M    2499 non-null   object
 116  DP05_0029MA   1 non-null      object
 117  DP05_0029EA   1 non-null      object
 118  DP05_0030E    2499 non-null   object
 119  DP05_0030M    2499 non-null   object
 120  DP05_0030MA   1 non-null      object
 121  DP05_0030EA   1 non-null      object
 122  DP05_0031E    2499 non-null   object
 123  DP05_0031M    2499 non-null   object
 124  DP05_0031MA   1 non-null      object
 125  DP05_0031EA   1 non-null      object
 126  DP05_0032E    2499 non-null   object
 127  DP05_0032M    2499 non-null   object
 128  DP05_0032MA   50 non-null     object
 129  DP05_0032EA   50 non-null     object
 130  DP05_0033E    2499 non-null   object
 131  DP05_0033EA   1 non-null      object
 132  DP05_0033M    2499 non-null   object
 133  DP05_0033MA   1 non-null      object
 134  DP05_0034E    2499 non-null   object
 135  DP05_0034M    2499 non-null   object
 136  DP05_0034MA   1 non-null      object
 137  DP05_0034EA   1 non-null      object
 138  DP05_0035E    2499 non-null   object
 139  DP05_0035M    2499 non-null   object
 140  DP05_0035MA   1 non-null      object
 141  DP05_0035EA   1 non-null      object
 142  DP05_0036E    2499 non-null   object
 143  DP05_0036M    2499 non-null   object
 144  DP05_0036MA   1 non-null      object
 145  DP05_0036EA   1 non-null      object
 146  DP05_0037E    2499 non-null   object
 147  DP05_0037M    2499 non-null   object
 148  DP05_0037MA   1 non-null      object
 149  DP05_0037EA   1 non-null      object
 150  DP05_0038E    2499 non-null   object
 151  DP05_0038M    2499 non-null   object
 152  DP05_0038MA   1 non-null      object
 153  DP05_0038EA   1 non-null      object
 154  DP05_0039E    2499 non-null   object
 155  DP05_0039M    2499 non-null   object
 156  DP05_0039MA   1 non-null      object
 157  DP05_0039EA   1 non-null      object
 158  DP05_0040E    2499 non-null   object
 159  DP05_0040M    2499 non-null   object
 160  DP05_0040MA   1 non-null      object
 161  DP05_0040EA   1 non-null      object
 162  DP05_0041E    2499 non-null   object
 163  DP05_0041M    2499 non-null   object
 164  DP05_0041MA   1 non-null      object
 165  DP05_0041EA   1 non-null      object
 166  DP05_0042E    2499 non-null   object
 167  DP05_0042M    2499 non-null   object
 168  DP05_0042MA   1 non-null      object
 169  DP05_0042EA   1 non-null      object
 170  DP05_0043E    2499 non-null   object
 171  DP05_0043M    2499 non-null   object
 172  DP05_0043MA   1 non-null      object
 173  DP05_0043EA   1 non-null      object
 174  DP05_0044E    2499 non-null   object
 175  DP05_0044M    2499 non-null   object
 176  DP05_0044MA   1 non-null      object
 177  DP05_0044EA   1 non-null      object
 178  DP05_0045E    2499 non-null   object
 179  DP05_0045EA   1 non-null      object
 180  DP05_0045M    2499 non-null   object
 181  DP05_0045MA   1 non-null      object
 182  DP05_0046E    2499 non-null   object
 183  DP05_0046M    2499 non-null   object
 184  DP05_0046MA   1 non-null      object
 185  DP05_0046EA   1 non-null      object
 186  DP05_0047E    2499 non-null   object
 187  DP05_0047M    2499 non-null   object
 188  DP05_0047MA   1 non-null      object
 189  DP05_0047EA   1 non-null      object
 190  DP05_0048E    2499 non-null   object
 191  DP05_0048M    2499 non-null   object
 192  DP05_0048MA   1 non-null      object
 193  DP05_0048EA   1 non-null      object
 194  DP05_0049E    2499 non-null   object
 195  DP05_0049M    2499 non-null   object
 196  DP05_0049MA   1 non-null      object
 197  DP05_0049EA   1 non-null      object
 198  DP05_0050E    2499 non-null   object
 199  DP05_0050M    2499 non-null   object
 200  DP05_0050MA   1 non-null      object
 201  DP05_0050EA   1 non-null      object
 202  DP05_0051E    2499 non-null   object
 203  DP05_0051M    2499 non-null   object
 204  DP05_0051MA   1 non-null      object
 205  DP05_0051EA   1 non-null      object
 206  DP05_0052E    2499 non-null   object
 207  DP05_0052M    2499 non-null   object
 208  DP05_0052MA   1 non-null      object
 209  DP05_0052EA   1 non-null      object
 210  DP05_0053E    2499 non-null   object
 211  DP05_0053EA   1 non-null      object
 212  DP05_0053M    2499 non-null   object
 213  DP05_0053MA   1 non-null      object
 214  DP05_0054E    2499 non-null   object
 215  DP05_0054M    2499 non-null   object
 216  DP05_0054MA   1 non-null      object
 217  DP05_0054EA   1 non-null      object
 218  DP05_0055E    2499 non-null   object
 219  DP05_0055M    2499 non-null   object
 220  DP05_0055MA   1 non-null      object
 221  DP05_0055EA   1 non-null      object
 222  DP05_0056E    2499 non-null   object
 223  DP05_0056EA   1 non-null      object
 224  DP05_0056M    2499 non-null   object
 225  DP05_0056MA   1 non-null      object
 226  DP05_0057E    2499 non-null   object
 227  DP05_0057M    2499 non-null   object
 228  DP05_0057MA   1 non-null      object
 229  DP05_0057EA   1 non-null      object
 230  DP05_0058E    2499 non-null   object
 231  DP05_0058M    2499 non-null   object
 232  DP05_0058MA   1 non-null      object
 233  DP05_0058EA   1 non-null      object
 234  DP05_0059E    2499 non-null   object
 235  DP05_0059M    2499 non-null   object
 236  DP05_0059MA   1 non-null      object
 237  DP05_0059EA   1 non-null      object
 238  DP05_0060E    2499 non-null   object
 239  DP05_0060M    2499 non-null   object
 240  DP05_0060MA   1 non-null      object
 241  DP05_0060EA   1 non-null      object
 242  DP05_0061E    2499 non-null   object
 243  DP05_0061M    2499 non-null   object
 244  DP05_0061MA   1 non-null      object
 245  DP05_0061EA   1 non-null      object
 246  DP05_0062E    2499 non-null   object
 247  DP05_0062M    2499 non-null   object
 248  DP05_0062MA   1 non-null      object
 249  DP05_0062EA   1 non-null      object
 250  DP05_0063E    2499 non-null   object
 251  DP05_0063M    2499 non-null   object
 252  DP05_0063MA   1 non-null      object
 253  DP05_0063EA   1 non-null      object
 254  DP05_0064E    2499 non-null   object
 255  DP05_0064M    2499 non-null   object
 256  DP05_0064MA   1 non-null      object
 257  DP05_0064EA   1 non-null      object
 258  DP05_0065E    2499 non-null   object
 259  DP05_0065M    2499 non-null   object
 260  DP05_0065MA   1 non-null      object
 261  DP05_0065EA   1 non-null      object
 262  DP05_0066E    2499 non-null   object
 263  DP05_0066M    2499 non-null   object
 264  DP05_0066MA   1 non-null      object
 265  DP05_0066EA   1 non-null      object
 266  DP05_0067E    2499 non-null   object
 267  DP05_0067EA   1 non-null      object
 268  DP05_0067M    2499 non-null   object
 269  DP05_0067MA   1 non-null      object
 270  DP05_0068E    2499 non-null   object
 271  DP05_0068M    2499 non-null   object
 272  DP05_0068MA   1 non-null      object
 273  DP05_0068EA   1 non-null      object
 274  DP05_0069E    2499 non-null   object
 275  DP05_0069M    2499 non-null   object
 276  DP05_0069MA   1 non-null      object
 277  DP05_0069EA   1 non-null      object
 278  DP05_0070E    2499 non-null   object
 279  DP05_0070M    2499 non-null   object
 280  DP05_0070MA   1 non-null      object
 281  DP05_0070EA   1 non-null      object
 282  DP05_0071E    2499 non-null   object
 283  DP05_0071M    2499 non-null   object
 284  DP05_0071MA   1 non-null      object
 285  DP05_0071EA   1 non-null      object
 286  DP05_0072E    2499 non-null   object
 287  DP05_0072M    2499 non-null   object
 288  DP05_0072MA   1 non-null      object
 289  DP05_0072EA   1 non-null      object
 290  DP05_0073E    2499 non-null   object
 291  DP05_0073M    2499 non-null   object
 292  DP05_0073MA   1 non-null      object
 293  DP05_0073EA   1 non-null      object
 294  DP05_0074E    2499 non-null   object
 295  DP05_0074M    2499 non-null   object
 296  DP05_0074MA   1 non-null      object
 297  DP05_0074EA   1 non-null      object
 298  DP05_0075E    2499 non-null   object
 299  DP05_0075M    2499 non-null   object
 300  DP05_0075MA   1 non-null      object
 301  DP05_0075EA   1 non-null      object
 302  DP05_0076E    2499 non-null   object
 303  DP05_0076M    2499 non-null   object
 304  DP05_0076MA   1 non-null      object
 305  DP05_0076EA   1 non-null      object
 306  DP05_0077E    2499 non-null   object
 307  DP05_0077M    2499 non-null   object
 308  DP05_0077MA   1 non-null      object
 309  DP05_0077EA   1 non-null      object
 310  DP05_0078E    2499 non-null   object
 311  DP05_0078EA   1 non-null      object
 312  DP05_0078M    2499 non-null   object
 313  DP05_0078MA   1 non-null      object
 314  DP05_0079E    2499 non-null   object
 315  DP05_0079M    2499 non-null   object
 316  DP05_0079MA   1 non-null      object
 317  DP05_0079EA   1 non-null      object
 318  DP05_0080E    2499 non-null   object
 319  DP05_0080M    2499 non-null   object
 320  DP05_0080MA   1 non-null      object
 321  DP05_0080EA   1 non-null      object
 322  DP05_0081E    2499 non-null   object
 323  DP05_0081M    2499 non-null   object
 324  DP05_0081MA   1 non-null      object
 325  DP05_0081EA   1 non-null      object
 326  DP05_0082E    2499 non-null   object
 327  DP05_0082M    2499 non-null   object
 328  DP05_0082MA   1 non-null      object
 329  DP05_0082EA   1 non-null      object
 330  DP05_0083E    2499 non-null   object
 331  DP05_0083M    2499 non-null   object
 332  DP05_0083MA   1 non-null      object
 333  DP05_0083EA   1 non-null      object
 334  DP05_0084E    2499 non-null   object
 335  DP05_0084M    2499 non-null   object
 336  DP05_0084MA   1 non-null      object
 337  DP05_0084EA   1 non-null      object
 338  DP05_0085E    2499 non-null   object
 339  DP05_0085M    2499 non-null   object
 340  DP05_0085MA   1 non-null      object
 341  DP05_0085EA   1 non-null      object
 342  DP05_0086E    2499 non-null   object
 343  DP05_0086M    2499 non-null   object
 344  DP05_0086MA   1 non-null      object
 345  DP05_0086EA   1 non-null      object
 346  DP05_0087E    2499 non-null   object
 347  DP05_0087M    2499 non-null   object
 348  DP05_0087MA   1 non-null      object
 349  DP05_0087EA   1 non-null      object
 350  DP05_0088E    2499 non-null   object
 351  DP05_0088M    2499 non-null   object
 352  DP05_0088MA   1 non-null      object
 353  DP05_0088EA   1 non-null      object
 354  DP05_0089E    2499 non-null   object
 355  DP05_0089EA   1 non-null      object
 356  DP05_0089M    2499 non-null   object
 357  DP05_0089MA   1 non-null      object
 358  DP05_0001PE   2499 non-null   object
 359  DP05_0001PM   2499 non-null   object
 360  DP05_0001PMA  2499 non-null   object
 361  DP05_0001PEA  1 non-null      object
 362  DP05_0002PE   2499 non-null   object
 363  DP05_0002PM   2499 non-null   object
 364  DP05_0002PMA  21 non-null     object
 365  DP05_0002PEA  21 non-null     object
 366  DP05_0003PE   2499 non-null   object
 367  DP05_0003PM   2499 non-null   object
 368  DP05_0003PMA  21 non-null     object
 369  DP05_0003PEA  21 non-null     object
 370  DP05_0004PE   2499 non-null   object
 371  DP05_0004PM   2499 non-null   object
 372  DP05_0004PMA  2499 non-null   object
 373  DP05_0004PEA  2499 non-null   object
 374  DP05_0005PE   2499 non-null   object
 375  DP05_0005PEA  21 non-null     object
 376  DP05_0005PM   2499 non-null   object
 377  DP05_0005PMA  21 non-null     object
 378  DP05_0006PE   2499 non-null   object
 379  DP05_0006PM   2499 non-null   object
 380  DP05_0006PMA  21 non-null     object
 381  DP05_0006PEA  21 non-null     object
 382  DP05_0007PE   2499 non-null   object
 383  DP05_0007PM   2499 non-null   object
 384  DP05_0007PMA  21 non-null     object
 385  DP05_0007PEA  21 non-null     object
 386  DP05_0008PE   2499 non-null   object
 387  DP05_0008PM   2499 non-null   object
 388  DP05_0008PMA  21 non-null     object
 389  DP05_0008PEA  21 non-null     object
 390  DP05_0009PE   2499 non-null   object
 391  DP05_0009PM   2499 non-null   object
 392  DP05_0009PMA  21 non-null     object
 393  DP05_0009PEA  21 non-null     object
 394  DP05_0010PE   2499 non-null   object
 395  DP05_0010PM   2499 non-null   object
 396  DP05_0010PMA  21 non-null     object
 397  DP05_0010PEA  21 non-null     object
 398  DP05_0011PE   2499 non-null   object
 399  DP05_0011PM   2499 non-null   object
 400  DP05_0011PMA  21 non-null     object
 401  DP05_0011PEA  21 non-null     object
 402  DP05_0012PE   2499 non-null   object
 403  DP05_0012PM   2499 non-null   object
 404  DP05_0012PMA  21 non-null     object
 405  DP05_0012PEA  21 non-null     object
 406  DP05_0013PE   2499 non-null   object
 407  DP05_0013PM   2499 non-null   object
 408  DP05_0013PMA  21 non-null     object
 409  DP05_0013PEA  21 non-null     object
 410  DP05_0014PE   2499 non-null   object
 411  DP05_0014PM   2499 non-null   object
 412  DP05_0014PMA  21 non-null     object
 413  DP05_0014PEA  21 non-null     object
 414  DP05_0015PE   2499 non-null   object
 415  DP05_0015PM   2499 non-null   object
 416  DP05_0015PMA  21 non-null     object
 417  DP05_0015PEA  21 non-null     object
 418  DP05_0016PE   2499 non-null   object
 419  DP05_0016PM   2499 non-null   object
 420  DP05_0016PMA  21 non-null     object
 421  DP05_0016PEA  21 non-null     object
 422  DP05_0017PE   2499 non-null   object
 423  DP05_0017PM   2499 non-null   object
 424  DP05_0017PMA  21 non-null     object
 425  DP05_0017PEA  21 non-null     object
 426  DP05_0018PE   2499 non-null   object
 427  DP05_0018PM   2499 non-null   object
 428  DP05_0018PMA  2499 non-null   object
 429  DP05_0018PEA  2499 non-null   object
 430  DP05_0019PE   2499 non-null   object
 431  DP05_0019PM   2499 non-null   object
 432  DP05_0019PMA  21 non-null     object
 433  DP05_0019PEA  21 non-null     object
 434  DP05_0020PE   2499 non-null   object
 435  DP05_0020PEA  21 non-null     object
 436  DP05_0020PM   2499 non-null   object
 437  DP05_0020PMA  21 non-null     object
 438  DP05_0021PE   2499 non-null   object
 439  DP05_0021PM   2499 non-null   object
 440  DP05_0021PMA  21 non-null     object
 441  DP05_0021PEA  21 non-null     object
 442  DP05_0022PE   2499 non-null   object
 443  DP05_0022PM   2499 non-null   object
 444  DP05_0022PMA  21 non-null     object
 445  DP05_0022PEA  21 non-null     object
 446  DP05_0023PE   2499 non-null   object
 447  DP05_0023PM   2499 non-null   object
 448  DP05_0023PMA  21 non-null     object
 449  DP05_0023PEA  21 non-null     object
 450  DP05_0024PE   2499 non-null   object
 451  DP05_0024PM   2499 non-null   object
 452  DP05_0024PMA  21 non-null     object
 453  DP05_0024PEA  21 non-null     object
 454  DP05_0025PE   2499 non-null   object
 455  DP05_0025PM   2499 non-null   object
 456  DP05_0025PMA  2499 non-null   object
 457  DP05_0025PEA  1 non-null      object
 458  DP05_0026PE   2499 non-null   object
 459  DP05_0026PM   2499 non-null   object

In [5]:
la_county_df.dropna(axis=1, inplace=True)
la_county_df.head()

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,...,DP05_0086PM,DP05_0086PMA,DP05_0086PEA,DP05_0087PE,DP05_0087PM,DP05_0087PMA,DP05_0088PE,DP05_0088PM,DP05_0089PE,DP05_0089PM
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent Margin of Error!!Total housing units,Annotation of Percent Margin of Error!!Total h...,Annotation of Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",Annotation of Percent Margin of Error!!CITIZEN...,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P..."
1,1400000US06037101110,"Census Tract 1011.10, Los Angeles County, Cali...",3879,480,1944,280,1935,294,100.5,16.1,...,(X),(X),(X),2932,(X),(X),46.6,4.0,53.4,4.0
2,1400000US06037101122,"Census Tract 1011.22, Los Angeles County, Cali...",4247,875,2066,477,2181,457,94.7,14.7,...,(X),(X),(X),3342,(X),(X),51.3,4.2,48.7,4.2
3,1400000US06037101220,"Census Tract 1012.20, Los Angeles County, Cali...",3583,486,1692,262,1891,307,89.5,14.7,...,(X),(X),(X),2463,(X),(X),46.9,5.4,53.1,5.4
4,1400000US06037101221,"Census Tract 1012.21, Los Angeles County, Cali...",3723,721,1954,470,1769,406,110.5,29.3,...,(X),(X),(X),2177,(X),(X),57.2,9.0,42.8,9.0

In [6]:
la_county_data = la_county_df[['GEO_ID', 'NAME', 'DP05_0063E', 'DP05_0063M', 'DP05_0064E', 'DP05_0064M',
                              'DP05_0065E', 'DP05_0065M', 'DP05_0067E', 'DP05_0067M', 'DP05_0071E', 'DP05_0071M']]
la_county_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   GEO_ID      2499 non-null   object
 1   NAME        2499 non-null   object
 2   DP05_0063E  2499 non-null   object
 3   DP05_0063M  2499 non-null   object
 4   DP05_0064E  2499 non-null   object
 5   DP05_0064M  2499 non-null   object
 6   DP05_0065E  2499 non-null   object
 7   DP05_0065M  2499 non-null   object
 8   DP05_0067E  2499 non-null   object
 9   DP05_0067M  2499 non-null   object
 10  DP05_0071E  2499 non-null   object
 11  DP05_0071M  2499 non-null   object
dtypes: object(12)
memory usage: 234.4+ KB

In [7]:
la_county_data

,GEO_ID,NAME,DP05_0063E,DP05_0063M,DP05_0064E,DP05_0064M,DP05_0065E,DP05_0065M,DP05_0067E,DP05_0067M,DP05_0071E,DP05_0071M
0,Geography,Geographic Area Name,Estimate!!Race alone or in combination with on...,Margin of Error!!Race alone or in combination ...,Estimate!!Race alone or in combination with on...,Margin of Error!!Race alone or in combination ...,Estimate!!Race alone or in combination with on...,Margin of Error!!Race alone or in combination ...,Estimate!!Race alone or in combination with on...,Margin of Error!!Race alone or in combination ...,Estimate!!HISPANIC OR LATINO AND RACE!!Total p...,Margin of Error!!HISPANIC OR LATINO AND RACE!!...
1,1400000US06037101110,"Census Tract 1011.10, Los Angeles County, Cali...",3879,480,3174,420,73,53,442,114,1005,381
2,1400000US06037101122,"Census Tract 1011.22, Los Angeles County, Cali...",4247,875,3272,852,144,118,752,309,339,218
3,1400000US06037101220,"Census Tract 1012.20, Los Angeles County, Cali...",3583,486,2531,489,23,27,371,178,1783,450
4,1400000US06037101221,"Census Tract 1012.21, Los Angeles County, Cali...",3723,721,2685,642,128,97,273,232,1203,395
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,1400000US06037980038,"Census Tract 9800.38, Los Angeles County, Cali...",0,13,0,13,0,13,0,13,0,13
2495,1400000US06037980039,"Census Tract 9800.39, Los Angeles County, Cali...",0,13,0,13,0,13,0,13,0,13
2496,1400000US06037990100,"Census Tract 9901, Los Angeles County, California",0,13,0,13,0,13,0,13,0,13
2497,1400000US06037990200,"Census Tract 9902, Los Angeles County, California",0,13,0,13,0,13,0,13,0,13
2498,1400000US06037990300,"Census Tract 9903, Los Angeles County, California",0,13,0,13,0,13,0,13,0,13

In [8]:
la_county_data.columns = la_county_data.iloc[0]

In [9]:
la_county_final = la_county_data.drop(la_county_data.index[0])

In [10]:
la_county_final.reset_index(drop=True, inplace=True)
la_county_final

,Geography,Geographic Area Name,Estimate!!Race alone or in combination with one or more other races!!Total population,Margin of Error!!Race alone or in combination with one or more other races!!Total population,Estimate!!Race alone or in combination with one or more other races!!Total population!!White,Margin of Error!!Race alone or in combination with one or more other races!!Total population!!White,Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Margin of Error!!Race alone or in combination with one or more other races!!Total population!!Black or African American,Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian,Margin of Error!!Race alone or in combination with one or more other races!!Total population!!Asian,Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race),Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)
0,1400000US06037101110,"Census Tract 1011.10, Los Angeles County, Cali...",3879,480,3174,420,73,53,442,114,1005,381
1,1400000US06037101122,"Census Tract 1011.22, Los Angeles County, Cali...",4247,875,3272,852,144,118,752,309,339,218
2,1400000US06037101220,"Census Tract 1012.20, Los Angeles County, Cali...",3583,486,2531,489,23,27,371,178,1783,450
3,1400000US06037101221,"Census Tract 1012.21, Los Angeles County, Cali...",3723,721,2685,642,128,97,273,232,1203,395
4,1400000US06037101222,"Census Tract 1012.22, Los Angeles County, Cali...",2690,520,2443,483,17,29,131,197,915,667
...,...,...,...,...,...,...,...,...,...,...,...,...
2493,1400000US06037980038,"Census Tract 9800.38, Los Angeles County, Cali...",0,13,0,13,0,13,0,13,0,13
2494,1400000US06037980039,"Census Tract 9800.39, Los Angeles County, Cali...",0,13,0,13,0,13,0,13,0,13
2495,1400000US06037990100,"Census Tract 9901, Los Angeles County, California",0,13,0,13,0,13,0,13,0,13
2496,1400000US06037990200,"Census Tract 9902, Los Angeles County, California",0,13,0,13,0,13,0,13,0,13
2497,1400000US06037990300,"Census Tract 9903, Los Angeles County, California",0,13,0,13,0,13,0,13,0,13

In [11]:
la_county_final.columns = ['Geography', 'Geographic Area Name', 'Total population', 'Error!Total population', 'Total population!!White',
                                'Error!Total population!!White', 'Total population!!Black or African American', 'Error!Total population!!Black or African American',
                                'Total population!!Asian', 'Error!Total population!!Asian',
                                'Total population!!Hispanic or Latino (of any race)', 'Error!Total population!!Hispanic or Latino (of any race)']
la_county_final.head()

,Geography,Geographic Area Name,Total population,Error!Total population,Total population!!White,Error!Total population!!White,Total population!!Black or African American,Error!Total population!!Black or African American,Total population!!Asian,Error!Total population!!Asian,Total population!!Hispanic or Latino (of any race),Error!Total population!!Hispanic or Latino (of any race)
0,1400000US06037101110,"Census Tract 1011.10, Los Angeles County, Cali...",3879,480,3174,420,73,53,442,114,1005,381
1,1400000US06037101122,"Census Tract 1011.22, Los Angeles County, Cali...",4247,875,3272,852,144,118,752,309,339,218
2,1400000US06037101220,"Census Tract 1012.20, Los Angeles County, Cali...",3583,486,2531,489,23,27,371,178,1783,450
3,1400000US06037101221,"Census Tract 1012.21, Los Angeles County, Cali...",3723,721,2685,642,128,97,273,232,1203,395
4,1400000US06037101222,"Census Tract 1012.22, Los Angeles County, Cali...",2690,520,2443,483,17,29,131,197,915,667

In [12]:
la_county_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2498 entries, 0 to 2497
Data columns (total 12 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Geography                                                 2498 non-null   object
 1   Geographic Area Name                                      2498 non-null   object
 2   Total population                                          2498 non-null   object
 3   Error!Total population                                    2498 non-null   object
 4   Total population!!White                                   2498 non-null   object
 5   Error!Total population!!White                             2498 non-null   object
 6   Total population!!Black or African American               2498 non-null   object
 7   Error!Total population!!Black or African American         2498 non-null   object
 8   Total population!!Asian                                   2498 non-null   object
 9   Error!Total population!!Asian                             2498 non-null   object
 10  Total population!!Hispanic or Latino (of any race)        2498 non-null   object
 11  Error!Total population!!Hispanic or Latino (of any race)  2498 non-null   object
dtypes: object(12)
memory usage: 234.3+ KB

In [13]:
la_county_final.iloc[:, 2:].astype(int).describe()

,Total population,Error!Total population,Total population!!White,Error!Total population!!White,Total population!!Black or African American,Error!Total population!!Black or African American,Total population!!Asian,Error!Total population!!Asian,Total population!!Hispanic or Latino (of any race),Error!Total population!!Hispanic or Latino (of any race)
count,2498.00000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000
mean,4011.06285,602.570056,2128.285028,496.698559,372.722178,181.953963,670.449560,221.797838,1953.010008,456.268215
std,1470.99188,242.111108,1139.757866,232.646368,551.262112,166.802046,761.135514,168.896018,1422.184921,259.591107
min,0.00000,6.000000,0.000000,4.000000,0.000000,2.000000,0.000000,2.000000,0.000000,4.000000
25%,2993.25000,441.250000,1300.500000,339.000000,69.000000,64.000000,164.000000,108.000000,752.000000,257.000000
50%,3933.00000,577.000000,1971.500000,465.000000,193.000000,137.000000,426.000000,187.000000,1691.500000,428.000000
75%,4954.00000,736.750000,2778.750000,615.000000,425.000000,243.000000,863.750000,293.000000,2929.500000,602.750000
max,13830.00000,2223.000000,7864.000000,2209.000000,5683.000000,1399.000000,5938.000000,1432.000000,8126.000000,2128.000000

In [14]:
la_county_final.to_csv("./data/census_data/LA_County_Cleaned_Data.csv", index=False)