In [1]:
## For data handling
import pandas as pd
import numpy as np

## For plotting
import matplotlib.pyplot as plt
import seaborn as sns

## This sets the plot style
## to have a grid on a white background
sns.set_style("whitegrid")

/Users/zoekearney/opt/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
# read in the final dataset 
df = pd.read_csv('../../data/cenus_epa_climate_theil_merged.csv')

In [9]:
for i in df.columns:
    print(i)

ID
NAME
pop_tot
pop_white_only
pop_black_only
pop_amInd_alNat_only
pop_asian_only
pop_natHI_PI_only
pop_white
pop_black
pop_amInd_alNat
pop_asian
pop_natHI_PI
pop_hispanic_latino_any
poverty_tot_white_only
poverty_tot_black_only
poverty_tot_amInd_alNat_only
poverty_tot_asian_only
poverty_tot_natHI_PI_only
poverty_tot_hispanic_latino_any
poverty_below_white_only
poverty_below_black_only
poverty_below_amInd_alNat_only
poverty_below_asian_only
poverty_below_natHI_PI_only
poverty_below_hispanic_latino_any
poverty_below_white_only.1
poverty_perc_black_only
poverty_perc_amInd_alNat_only
poverty_perc_asian_only
poverty_perc_natHI_PI_only
poverty_perc_hispanic_latino_any
industry_tot
industry_ag_for
industry_const
industry_manu
industry_wtrade
industry_rtrade
industry_transp
industry_info
industry_fin
industry_prof
industry_ed_hc
industry_arts_ent
industry_other
industry_pub_admin
income_tot
income_under10k
income_10to15k
income_15to25k
income_25to35k
income_35to50k
income_50to75k
income_75to100k
income_100to150k
income_150to200k
income_over200k
income_median
health_ins_tot
health_ins_yes
health_ins_no
OID_
STATE_NAME
ST_ABBREV
CNTY_NAME
REGION
AREALAND
AREAWATER
PM25
OZONE
DSLPM
CANCER
RESP
RSEI_AIR
PTRAF
PRE1960
PRE1960PCT
PNPL
PRMP
PTSDF
UST
PWDIS
PN_PM25
PN_OZONE
PN_DSLPM
PN_CANCER
PN_RESP
PN_RSEI_AIR
PN_PTRAF
PN_LDPNT
PN_PNPL
PN_PRMP
PN_PTSDF
PN_UST
PN_PWDIS
PS_PM25
PS_OZONE
PS_DSLPM
PS_CANCER
PS_RESP
PS_RSEI_AIR
PS_PTRAF
PS_LDPNT
PS_PNPL
PS_PRMP
PS_PTSDF
PS_UST
PS_PWDIS
temp_labor_1 deg
temp_labor_2 deg
temp_labor_3 deg
temp_labor_4 deg
temp_labor_5 deg
pop_density
theil_income_tot
theil_pop_black
theil_pop_asian
theil_industry_tot

In [12]:
df_urban = df[df.pop_density >= 500]
df_urban = df_urban.reset_index(drop=True)

In [13]:
df_urban

,ID,NAME,pop_tot,pop_white_only,pop_black_only,pop_amInd_alNat_only,pop_asian_only,pop_natHI_PI_only,pop_white,pop_black,...,temp_labor_1 deg,temp_labor_2 deg,temp_labor_3 deg,temp_labor_4 deg,temp_labor_5 deg,pop_density,theil_income_tot,theil_pop_black,theil_pop_asian,theil_industry_tot
0,1001020200,"Census Tract 202, Autauga County, Alabama",2010.0,785.0,1088.0,0.0,0.0,0.0,882.0,1175.0,...,11.801866,26.030747,39.215973,52.425672,63.559917,605.272556,0.000010,-0.000009,0.000018,8.403355e-06
1,1001020300,"Census Tract 203, Autauga County, Alabama",3577.0,2433.0,983.0,0.0,26.0,0.0,2457.0,1105.0,...,11.801866,26.030747,39.215973,52.425672,63.559917,668.689248,0.000001,-0.000008,0.000008,2.348154e-07
2,1001020400,"Census Tract 204, Autauga County, Alabama",3802.0,3410.0,251.0,18.0,14.0,0.0,3519.0,268.0,...,11.801866,26.030747,39.215973,52.425672,63.559917,595.525072,-0.000001,0.000009,0.000024,3.642122e-07
3,1001020501,"Census Tract 205.01, Autauga County, Alabama",4381.0,3323.0,976.0,0.0,28.0,0.0,3348.0,1005.0,...,NaN,NaN,NaN,NaN,NaN,706.196703,-0.000002,-0.000007,0.000026,-3.269960e-06
4,1001020502,"Census Tract 205.02, Autauga County, Alabama",3328.0,2673.0,166.0,0.0,373.0,0.0,2732.0,166.0,...,NaN,NaN,NaN,NaN,NaN,1586.733988,0.000002,0.000014,-0.000006,4.338277e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49924,56033000400,"Census Tract 4, Sheridan County, Wyoming",5489.0,5233.0,0.0,8.0,12.0,0.0,5408.0,69.0,...,4.014716,11.349566,19.377176,33.097183,41.981195,886.002230,-0.000006,0.000024,0.000021,-4.577464e-06
49925,56037970602,"Census Tract 9706.02, Sweetwater County, Wyoming",3364.0,2777.0,0.0,194.0,14.0,0.0,3096.0,0.0,...,1.609278,6.331813,10.679828,20.037767,27.951797,2246.007228,0.000005,NaN,0.000014,2.632724e-06
49926,56037970902,"Census Tract 9709.02, Sweetwater County, Wyoming",5348.0,4491.0,209.0,52.0,77.0,0.0,4813.0,257.0,...,2.539311,8.102764,12.637384,22.608638,30.927471,735.764511,-0.000002,0.000009,0.000005,-4.195903e-06
49927,56039967801,"Census Tract 9678.01, Teton County, Wyoming",3134.0,2462.0,0.0,0.0,104.0,0.0,2514.0,0.0,...,NaN,NaN,NaN,NaN,NaN,501.253614,0.000002,NaN,0.000007,-2.753102e-06
49928,56043000301,"Census Tract 3.01, Washakie County, Wyoming",2208.0,1764.0,0.0,35.0,0.0,0.0,1987.0,47.0,...,3.483128,11.804527,18.827176,32.561037,42.184988,1107.766406,0.000005,0.000029,NaN,6.152564e-06

In [14]:
# set up the classificaiton of PM2.5 
# Anything greater than 9 is considered dangerous 

pm25_class = 
pm25 = df_urban['PM25']

0        9.722213
1        9.743874
2        9.766758
3        9.781263
4        9.781263
           ...
49924    4.052711
49925    5.130811
49926    4.951017
49927    2.865505
49928    3.465309
Name: PM25, Length: 49929, dtype: float64